/*==============================================================================
 * Copyright (C) 2011-2021 Macnica Inc. All Rights Reserved.
 *
 *  This program is proprietary and confidential. By using this program
 *  you agree to the terms of the associated Macnica Software License Agreement.
 * ------------------------------------------------------------------------------
 * ! @file
 * ! @brief  This file provides macro definiton of Nios2 assember code.
 *==============================================================================*/

/* .equ  SCHED_SUPPORT_TRACE_LOG,  1 */
.equ  SCHED_SUPPORT_INTERRUPT,  1
